# Generated by Django 5.2.5 on 2025-09-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default='Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('PROG', 'Programming'), ('DESIGN', 'Designing'), ('AI', 'Artificial Intelligence'), ('MATH', 'Mathematics'), ('BUISNESS', 'Buisness Communication')], max_length=20),
        ),
    ]
